-- A campaign can either use the fixed templates (default, free, instant) or
-- have its emails generated by Claude from a user-written prompt.
alter table public.campaigns
  add column generation_mode text not null default 'template'
    check (generation_mode in ('template', 'ai')),
  add column ai_prompt text;
